name: autonomous_vehicle
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - opencv
  - pillow
  - pip
  - tk
  - pygame
  - matplotlib
  - ipykernel
  - pip:
      - pyserial
      - rplidar-roboticia

